timeout 43200 /usr/bin/python /home/coffeyrt/311pull/311pull.py
/usr/bin/python /home/coffeyrt/311pull/311plot.py --database /media/main/Rory/311/311.db --out /media/main/Rory/311/
